Repository Activiti/activiti-cloud-audit, pull requests merged in 2018-11, with the labels that each got.

#41 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.75
  pom.xml
Labels: updatebot

#42 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.77
  pom.xml
Labels: updatebot

#43 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.81
  pom.xml
Labels: in progress, updatebot

#44 applying activiti cloud dep upgrade to master
  pom.xml
Labels: in progress

#46 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.91
  pom.xml
Labels: in progress, updatebot

#47 no bean overriding
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: in progress
