Repository Activiti/activiti-cloud-audit, pull requests merged in 2018-12, with the labels that each got.

#48 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.96
  pom.xml
Labels: in progress, updatebot

#52 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.100
  pom.xml
Labels: in progress, updatebot

#53 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.104
  pom.xml
Labels: in progress, updatebot

#56 Pr/50
  .dockerignore
  .mergify.yml
  .updatebot.yml
  Jenkinsfile
  Jenkinsfile.prow
  OWNERS
  OWNERS_ALIASES
  charts/activiti-cloud-audit/.helmignore
  charts/activiti-cloud-audit/Chart.yaml
  charts/activiti-cloud-audit/Makefile
  charts/activiti-cloud-audit/README.md
  charts/activiti-cloud-audit/requirements.yaml
  charts/activiti-cloud-audit/templates/NOTES.txt
  charts/activiti-cloud-audit/templates/_helpers.tpl
  charts/activiti-cloud-audit/templates/deployment.yaml
  charts/activiti-cloud-audit/templates/ingress.yaml
  charts/activiti-cloud-audit/templates/service.yaml
  charts/activiti-cloud-audit/values.yaml
  maven-dind.yaml
  skaffold.yaml
Labels: in progress

#55 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.106
  pom.xml
Labels: in progress, updatebot

#58 Update Jenkinsfile
  Jenkinsfile
Labels: in progress

#57 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.108
  pom.xml
Labels: in progress, updatebot

#60 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.109
  pom.xml
Labels: updatebot

#61 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.110
  pom.xml
Labels: updatebot

#63 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.113
  pom.xml
Labels: updatebot

#64 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.114
  pom.xml
Labels: updatebot

#65 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.115
  pom.xml
Labels: updatebot

#66 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.116
  pom.xml
Labels: updatebot

#67 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.117
  pom.xml
Labels: updatebot

#68 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.118
  pom.xml
Labels: updatebot

#69 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.119
  pom.xml
Labels: updatebot

#70 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.120
  pom.xml
Labels: updatebot

#71 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.121
  pom.xml
Labels: updatebot

#72 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.122
  pom.xml
Labels: updatebot

#73 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.123
  pom.xml
Labels: updatebot

#74 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.124
  pom.xml
Labels: updatebot

#75 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.125
  pom.xml
Labels: updatebot

#76 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.126
  pom.xml
Labels: updatebot

#77 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.127
  pom.xml
Labels: updatebot

#78 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.128
  pom.xml
Labels: updatebot

#80 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.130
  pom.xml
Labels: updatebot

#81 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.131
  pom.xml
Labels: updatebot

#82 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.132
  pom.xml
Labels: updatebot

#83 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.133
  pom.xml
Labels: updatebot
